---
# Router URL and credentials
router:
   label: "nram-dev1-solace-cloud" # used for dir name and logging purposes
   sempUrl: "https://mr-connection-xoqmdwtfgbe.messaging.solace.cloud:943/SEMP/v2/config"
   sempUser: "nram-dev1-admin"
   sempPassword: "**s3ul6rmga4fhihktckqj43td4f"

# VPN to work with
vpn:
   msgVpnNames: 
   - nram-dev1

# Template values for creating artifacts
templates:
   # Queue template to use for creating queues.
   # These values can be overwritten in the input CSV file
   # Any property not listed here / input CSV will use Solace defaults
   queue:
      accessType: "non-exclusive"
      deadMsgQueue: "#DEAD_MSG_QUEUE"
      maxBindCount: 10
      maxDeliveredUnackedMsgsPerFlow: 1000
      maxMsgSize: 1000000
      maxMsgSpoolUsage: 1234
      maxRedeliveryCount: 2
      maxTtl: 0
      owner: "solace-cloud-client"
      permission: "no-access"
      redeliveryEnabled: true
      respectTtlEnabled: true
      subscriptionTopic: ""
   dmqueue:
      accessType: "exclusive"
      deadMsgQueue: "#DEAD_MSG_QUEUE"
      maxBindCount: 1
      maxDeliveredUnackedMsgsPerFlow: 1000
      maxMsgSize: 1000000
      maxMsgSpoolUsage: 5000
      maxRedeliveryCount: 0
      maxTtl: 0
      owner: "solace-cloud-client"
      permission: "no-access"
      redeliveryEnabled: false
      respectTtlEnabled: false
      subscriptionTopic: ""

internal:
   systemConfig: "config/system.yaml"