name: Post on Change

on:
  push:
    paths:
      - 'input/**'

jobs:
  create_queues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install datetime logging requests pathlib pyyaml 

      - name: Run Python script
        run: |
          # Your script to detect changes and perform REST POST request
          #python scripts/create-queues2.py --input $file
          python scripts/create-queues2.py --input input/test-queues-002.yaml
        env:
          SEMP_PASSWORD: ${{ secrets.SEMP_PASSWORD }}
