name: Post on Change

on:
  push:
    paths:
      - 'input/**'

jobs:
  create_queues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Get uploaded or updated file names
      #   id: get_files
      #   run: |
      #     # Get the list of changed files
      #     # TODO - this doesn't work in the actions work flow
      #     # but works locally. Need to figure out why
      #     #files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
      #     # hard code for testing
      #     files="input/queues.yaml"
      #     # Set the output variable for later use
      #     echo "::set-output name=files::${files}"
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install datetime logging requests pathlib pyyaml 

      # - name: Run create-queues2 for each file
      #   run: |
      #     # Iterate over the list of changed files
      #     IFS=$'\n' read -rd '' -a files_array <<<"${{ steps.get_files.outputs.files }}"
      #     for file in "${files_array[@]}"; do
      #       # Run your desired steps for each file
      #       echo "Processing file: $file"
      #       python scripts/create-queues2.py --input "$file"
      #     done
      #   env:
      #     SEMP_PASSWORD: ${{ secrets.SEMP_PASSWORD }}

      - name: Run Python script - hardcoded input file
        run: |
          python scripts/create-queues2.py --input input/queues.yaml
        env:
          SEMP_PASSWORD: ${{ secrets.SEMP_PASSWORD }}
